# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
    apt-get update
    apt-get -y upgrade
    apt-get install -y nasm
    apt-get install -y gcc-multilib
    apt-get install -y build-essential nasm
    apt-get install -y gcc-multilib g++-multilib
    apt-get install -y software-properties-common
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 2002, host: 2002
  config.vm.provision "shell", inline: $script

end
