DROP TABLE IF EXISTS [Parts]
GO
DROP TABLE IF EXISTS [Inventory]
GO
DROP TABLE IF EXISTS [ServiceOrder]
GO
DROP TABLE IF EXISTS [OrderItem]
GO
DROP TABLE IF EXISTS [Progress]
GO
DROP TABLE IF EXISTS [Status]
GO
DROP TABLE IF EXISTS [DeviceType]
GO
DROP TABLE IF EXISTS [OrgUnit]
GO
DROP TABLE IF EXISTS [Client]
GO
DROP TABLE IF EXISTS [Team]
GO
DROP TABLE IF EXISTS [Employee]
GO
